/* 

	Student ID: 1155079510 
	Name : Wong Tsz Hin

*/

/* Query 1 */
SELECT LEAGUES.LID, LEAGUES.LEAGUE_NAME, LEAGUES.SEASON, TEAMS.TEAM_NAME
FROM LEAGUES
INNER JOIN TEAMS
ON LEAGUES.CHAMPION_TID = TEAMS.TID
WHERE TEAMS.TID IN (
SELECT TID FROM TEAMS WHERE AVERAGE_AGE = (SELECT MAX(AVERAGE_AGE) FROM TEAMS));

/* Query 2 */
SELECT TEAMS.TID, TEAMS.TEAM_NAME, LEAGUES.LEAGUE_NAME, LEAGUES.SEASON
FROM LEAGUES
INNER JOIN TEAMS
ON LEAGUES.CHAMPION_TID = TEAMS.TID
WHERE LEAGUES.YEAR = '2016' OR LEAGUES.YEAR = '2017'
ORDER BY TID;

/* Query 3 */
CREATE VIEW TEMP AS 
	SELECT W_NUM, CHAMPION_TID 
	FROM
		(SELECT CHAMPION_TID, COUNT(*) AS W_NUM
		FROM LEAGUES
		GROUP BY CHAMPION_TID)
	WHERE W_NUM >= 2;

SELECT TEMP.W_NUM ,TEAMS.TID, TEAMS.TEAM_NAME
FROM TEAMS
INNER JOIN TEMP
ON TEAMS.TID = TEMP.CHAMPION_TID
WHERE TEMP.W_NUM >= 2
ORDER BY TEMP.W_NUM DESC;

DROP VIEW TEMP;

/* Query 4 */
SELECT FOOTBALL_RANKING, RID, REGION_NAME 
FROM REGIONS
WHERE RID IN (
	SELECT RID
	FROM(
		SELECT RID, COUNT(SEASON) AS H_NUM
		FROM LEAGUES
		GROUP BY RID)
	WHERE H_NUM > 2)
ORDER BY FOOTBALL_RANKING ASC;

/* Query 5 */
CREATE VIEW SUPPORT_RECORD AS
	SELECT SID, COUNT(LID) AS S_COUNT
	FROM SUPPORT
	GROUP BY SID;

SELECT SUPPORT_RECORD.S_COUNT, SPONSORS.SID,SPONSORS.SPONSOR_NAME
FROM SPONSORS
INNER JOIN SUPPORT_RECORD
ON SUPPORT_RECORD.SID = SPONSORS.SID
ORDER BY S_COUNT DESC;

DROP VIEW SUPPORT_RECORD;

/* Query 6 */
SELECT SID, SPONSOR_NAME, MARKET_VALUE
FROM SPONSORS
WHERE SID IN (
	SELECT SID
	FROM SUPPORT
	WHERE LID IN (
		SELECT LID
		FROM LEAGUES
		WHERE RID IN (
			SELECT RID
			FROM REGIONS
			WHERE FOOTBALL_RANKING > 10))
	)
AND SID IN (
	SELECT SID
	FROM (
		SELECT SID, SUM(SPONSORSHIP) AS S_NUM
		FROM SUPPORT
		GROUP BY SID)
	WHERE S_NUM > 3.0
)
ORDER BY SID ASC;

/* Query 7 */
SELECT SID, SPONSOR_NAME
FROM SPONSORS
WHERE SID IN (
	SELECT SID 
	FROM SUPPORT
	WHERE LID IN (
		SELECT LID
		 FROM REGIONS
		 WHERE RID <> (
			 SELECT RID 
			 FROM REGIONS
			 WHERE REGION_NAME = 'Japan')
	)
)AND SID IN (
	SELECT SID 
	FROM (
		SELECT  SID, COUNT(LID) AS L_NUM
		FROM SUPPORT
		GROUP BY SID)
	WHERE L_NUM >= 2
)
ORDER BY SID ASC;

/* Query 8 */
SELECT RID, REGION_NAME
FROM REGIONS
WHERE RID IN (
	SELECT RID
	FROM LEAGUES
	WHERE LID IN (
		SELECT LID 
		FROM SUPPORT 
		WHERE SID = (
			SELECT SID
			FROM (
				SELECT SID , COUNT(*) AS S_NUM
				FROM SUPPORT
				GROUP BY SID)
			WHERE S_NUM = (
				SELECT MAX(S_NUM)
				FROM (
					SELECT SID , COUNT(*) AS S_NUM
					FROM SUPPORT
					GROUP BY SID)
			)
		)
	)
)
ORDER BY RID DESC;
	
