SELECT * FROM SPONSORS;
SELECT * FROM TEAMS;
SELECT * FROM REGIONS;
SELECT * FROM LEAGUES;
SELECT * FROM SUPPORT;

/* Query 1 */
SELECT L1.LID, L1.LEAGUE_NAME, L1.SEASON, T1.TEAM_NAME
FROM LEAGUES L1, TEAMS T1
WHERE L1.CHAMPION_TID = T1.TID
      AND T1.AVERAGE_AGE > ANY (SELECT T2.AVERAGE_AGE
                                FROM TEAMS T2);

/* Query 2 */
SELECT T2.TID, T2.TEAM_NAME, L2.LEAGUE_NAME, L2.SEASON
FROM TEAMS T2, LEAGUES L2
WHERE L2.CHAMPION_TID = T2.TID AND (L2.YEAR = '2016' OR L2.YEAR = '2017')
ORDER BY T2.TID ASC;

/* Query 3 */
SELECT W.W_NUM, T3.TID
FROM TEAMS T3
INNER JOIN (SELECT CHAMPION_TID, COUNT(*) AS W_NUM
            FROM LEAGUES L3
            GROUP BY L3.CHAMPION_TID) W ON W.CHAMPION_TID =  T3.TID

